### ISSUE TITLE
Add padm

### ISSUE THREAD

**Issue by mforets** [acroy/Expokit.jl#10]
The function `padm` from Expokit computes the matrix exponential exp(A) of a large sparse matrix  using Pade approximants.

A preliminary version is [in this branch](https://github.com/mforets/Expokit.jl/blob/master/src/padm.jl). Some results are [here](https://github.com/mforets/Expokit.jl/wiki/Results).

**Comment by acroy** [comment]
I suggest you create a PR for your implementation of `padm`. Then we can discuss and comment more efficiently.

**Comment by acroy** [comment]
Discussion continues in #14
