### ISSUE TITLE
Add chbv

### ISSUE THREAD

**Issue by acroy** [acroy/Expokit.jl#15]
Maybe we should also add [chbv](https://www.maths.uq.edu.au/expokit/matlab/chbv.m) for completeness. Seems to be straight-forward.

**Comment by mforets** [comment]
i'll take with this one.

**Comment by acroy** [comment]
Great! I would suggest to first implement it "as it is" in Expokit and then, in a second step, implement the interface we have now for `expmv` (in-place versions etc).

**Comment by mforets** [comment]
Ok, this is now PR #16
