### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by mforets** [acroy/Expokit.jl#32]
A bug that was fixed probably in https://github.com/acroy/Expokit.jl/pull/25 still exists in the current release version of `Expokit.jl` that people download with `Pkg.add("Expokit")`. I suggest to make a new release soon. 

(the error was found again [here](https://github.com/JuliaReach/LazySets.jl/issues/486#issuecomment-410785106))

**Comment by acroy** [comment]
Thanks! You are right. Tagging in progress: JuliaLang/METADATA.jl#16361

**Comment by acroy** [comment]
Done.
